{
    "token": 'mne6PHXNihC2Maac5KKSY0Pv_MHc7yN7Ydrh5pwgq0xhgzNifDOkmuUrvrZQtqxX5U-wG8T51m4Iz2n875YdTXtGn8vUaK2XRv2U79O2TEw00GLN-i5Um6Gv', 
    "study_id": '685520a71989e961b8d66248', 
    "max_concurrent_sessions": 50,
    "workload_checker_period": 60
}